### ISSUE TITLE
Deployment to Nexus on master without tagging possible

### ISSUE THREAD

**Issue by sven1103** [qbicsoftware/cookiecutter-templates-cli#28]
When performing a commit to the `master` branch, we recognised that the `war` files are deployed to the Nexus repository server, and there is no check, if a Github release has been done. 

This way, "release" Maven artifacts can be deployed on Nexus, without having a connected Github release tag, which is bad. The line responsible for this is: 

[https://github.com/qbicsoftware/cookiecutter-templates-cli/blob/6200b3b5114615346237d44b5169f007e3ffe579/common-files/%7B%7B%20cookiecutter.artifact_id%20%7D%7D/.travis.yml#L60](https://github.com/qbicsoftware/cookiecutter-templates-cli/blob/6200b3b5114615346237d44b5169f007e3ffe579/common-files/%7B%7B%20cookiecutter.artifact_id%20%7D%7D/.travis.yml#L60)

Adding `... AND tag = true'` to the condition will fix this and only deploy, when a Github release has been made.

**Comment by sven1103** [comment]
Sorry, small correction:

https://github.com/qbicsoftware/projectbrowser-portlet/blob/aeaef89852832771b08647a3462caed014712520/.travis.yml#L62

And this regex needs to be added, for building on tagged releases:


https://github.com/qbicsoftware/projectbrowser-portlet/blob/aeaef89852832771b08647a3462caed014712520/.travis.yml#L22

**Comment by chahuistle** [comment]
This is how `.travis.yml` looks like now:

```
...
branches:
  only:
  - master
  - development
  - /[0-9]*\.[0-9]*\.[0-9]*/ # adds release branches
...
deploy:
- skip_cleanup: true
  provider: script
  script: mvn ... deploy
  on:
    branch: master
    condition: '"$TRAVIS_EVENT_TYPE" = "push"'
    tags: true
```

After doing changes in `development`, I run the following commands:

```
$ git checkout master
$ git merge development
  ... edit files, etc.
$ git add .
$ git commit -m "Releasing version 1.2.3"
$ git tag -a 1.2.3 -m "Release 1.2.3: now with more punch and less ouch"
$ git push --follow-tags
```
I then go to Travis to check the build, which is not deployed. Travis reports:

  * `Skipping a deployment with the script provider because this branch is not permitted: master`
  * `Skipping a deployment with the script provider because this is not a tagged commit`

I guess I ended up reading the same GitHub issues and StackOverflow questions because, from what I could gather, `.travis.yml` seems to be properly configured (suggested solutions were to add a regex and add the `tags: true` bit), yet nothing I do seems to do the trick.

Can you provide an example of how did you get this to work?

**Comment by chahuistle** [comment]
I think I figured this one out and I guess it would be good to explain what's going on, lest someone spends a couple of hours trying to understand this issue.

The way we chose to make releases is by using [GitHub.com Releases](https://help.github.com/en/articles/creating-releases). Whenever a release is published, GitHub will create and push a tag. It is possible to manually create tags (i.e., using the `git tag` command), but it is more convenient to do it using GitHub.

Travis is able to detect pushed tags. If configured correctly, Travis sets the `TRAVIS_BRANCH` and `TRAVIS_TAG` environment variables to the tag name, e.g., `v1.2.3`. According to the [Travis' docs](https://docs.travis-ci.com/user/deployment/#conditional-releases-with-on), setting `deploy.on.tags` to either `true` or `false` will result in `deploy.on.branch` to be ignored. This makes sense, because git tags are associated to commits, not to branches.

Putting all this together in `.travis.yml` looks like:

```
branches:
  only:
  - master
  - development
  - /some-regex-that-matches-release-version-strings/

...

deploy:
- skip_cleanup: true
  provider: script
  script: echo "Deploying a SNAPSHOT version to Nexus"
  on:
    branch: development
    condition: '"$TRAVIS_EVENT_TYPE" = "push"'
- skip_cleanup: true
  provider: script
  script: echo "Deploying a release to Nexus"
  on:
    condition: '"$TRAVIS_EVENT_TYPE" = "push"'
    tags: true
```

This configuration will make Travis to observe these rules:

  1. Builds will be performed against the `master`, `development` branches. Also--and this is just Travis trickery--since Travis treats pushed tags as branches, any tag whose name matches the given regex will also trigger a build and will *look like* a branch. 
![image](https://user-images.githubusercontent.com/1537189/55061868-68e9f880-503a-11e9-9582-395dacdb7efe.png)
  1. Any commit on the `development` branch will trigger a deployment.
  1. Any pushed tag that matches the given regex on `branches.only` will trigger a release deployment. 

Since git tags are just a way to label commits and are not bound to any branch, at least some validation should be performed before deploying release artifacts to Nexus. In our case, we use Maven to verify that version strings in `pom.xml` are valid release version strings (e.g, `1.2.3` and not `1.2.3-SNAPSHOT`).
